dataset_name: wikitext
dataset_config_name: wikitext-2-raw-v1
streaming: False

# num of process in data processing
num_proc: 1

# whether to load dataset from cache
load_from_cache_file: True

shuffle_buffer_size: 256